name: Deploy Portfolio

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy frontend
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend
          branch: gh-pages
